name: Build Android apk

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.RELEASE_KEYSTORE }}
      run: |
        echo $ENCODED_STRING | base64 --decode > release.jks

    - name: Build with Gradle
      env:
        RELEASE_STORE_FILE: ../release.jks
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk

    - name: Generate Artifact Attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'app/build/outputs/apk/release/*.apk'

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        generate_release_notes: true
        files: |
          app/build/outputs/apk/release/*.apk
